name: Run a test

on:
  push:
  pull_request:

jobs:
 test:
    runs-on: windows-latest
    steps: 
       
     - name: Inno Setup Action (push)
       uses: Minionguyjpro/Inno-Setup-Action@main
       with:
         path: test.iss
